#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.12

pipelines:
  default:
    - parallel:
      - step:
          name: Django Company API tests
          caches:
            - pip
          script:
            - pip install pipenv --upgrade
            - pipenv install --system
            - pip install pytest-cov
            - pytest api/coronavstech -s -v --durations=0 --cov=. -m "not skip_in_ci"
      - step:
          name: Fibonacci tests
          caches:
            - pip
          script:
            - pip install pipenv --upgrade
            - pip install pytest-cov
            - pipenv install --system
            - pytest fibonacci/ -s -v --durations=0 --cov=.

